<a href="https://colab.research.google.com/github/GangaSuresh/ANN_First/blob/main/Copy_of_DLCrash_May.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
# Importing the dataset
dataset = pd.read_csv('/Churn_Modelling.csv')
#features independent variables that have impact
X = dataset.iloc[:, 3:12].values
#dependent variable, if customer leaves the bank or not
y = dataset.iloc[:, -1].values
#print(X)
#print(y)

In [ ]:
#encoding categorical data
#change country and gender
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
#country
labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])
#gender
labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])
#to binary only country so we get in 0s and 1s not 0 1 and 2, no need for gender as already 0 and 1
#onehotencoder=OneHotEncoder(categorical_features=[1])
# Country column
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
#X = ct.fit_transform(X)
X=ct.fit_transform(X)
print(X[0:10,:])
#to remove dummy variable trap remove 1st col
X=X[:,1:]
print(X[0:10,:])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1]
 [0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1]
 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0]
 [1.0 0.0 0.0 699 0 39 1 0.0 2 0 0]
 [0.0 0.0 1.0 850 0 43 2 125510.82 1 1 1]
 [0.0 0.0 1.0 645 1 44 8 113755.78 2 1 0]
 [1.0 0.0 0.0 822 1 50 7 0.0 2 1 1]
 [0.0 1.0 0.0 376 0 29 4 115046.74 4 1 0]
 [1.0 0.0 0.0 501 1 44 4 142051.07 2 0 1]
 [1.0 0.0 0.0 684 1 27 2 134603.88 1 1 1]]
[[0.0 0.0 619 0 42 2 0.0 1 1 1]
 [0.0 1.0 608 0 41 1 83807.86 1 0 1]
 [0.0 0.0 502 0 42 8 159660.8 3 1 0]
 [0.0 0.0 699 0 39 1 0.0 2 0 0]
 [0.0 1.0 850 0 43 2 125510.82 1 1 1]
 [0.0 1.0 645 1 44 8 113755.78 2 1 0]
 [0.0 0.0 822 1 50 7 0.0 2 1 1]
 [1.0 0.0 376 0 29 4 115046.74 4 1 0]
 [0.0 0.0 501 1 44 4 142051.07 2 0 1]
 [0.0 0.0 684 1 27 2 134603.88 1 1 1]]


In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)



In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train[1,:])
print(X_test.size)

[ 1.75486502 -0.57369368 -2.30455945  0.91601335  0.30102557 -1.37744033
 -0.00631193 -0.92159124  0.64259497  0.9687384 ]
20000


***Done with preprocessing, start with ANN***


In [ ]:
#import keras and other packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
#initializing the ANN
classifier = Sequential() #NN model the classifier , make object
#input layer number of nodes is number of independent variables here 11
#dense module will take take of step1 ie assigning random weights close to 0
#rectifier function for hidden layers and sigmoid for output layer as we wnt the probability yes or no

#add input layer and first hidden layer, not adding io layer more like adding hidden which gets from io layer
#number of nodes in hidden layer no strict rule, based on experiment usually avg of nodes input and output layer(11+1)/2=6

#init is uniform to uniformly increase weights
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=10))
#2nd hidden layer, no need of input nodes
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

#output layer, only 1 node and sigmoid activation function
#Note- if last layer has more classes or categories yes, no ,maybe after one hot encoding it will have 3 outputs so 
# 3 nodes in end , also multi class use softmax function
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

#compile the ann, add gradient descent
#optimizer - to find best weights which algo like stochastic gradient descent here called adam
#loss funtion- difference btw actual value and predicted value to minimize, if many categories use categorical_crossentropy
#metrics - list of metrix to evaluate the model here accuracy
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

#connect or fit ANN to training set
#batch size to see after how many rows should the weights change, and epochs the total number whole dataset
classifier.fit(X_train,y_train,batch_size=10,epochs=100)



Epoch 1/100
800/800 [==============================] - 1s 948us/step - loss: 0.5754 - accuracy: 0.7854
Epoch 2/100
800/800 [==============================] - 1s 986us/step - loss: 0.4378 - accuracy: 0.7865
Epoch 3/100
800/800 [==============================] - 1s 962us/step - loss: 0.4121 - accuracy: 0.8066
Epoch 4/100
800/800 [==============================] - 1s 969us/step - loss: 0.4156 - accuracy: 0.8238
Epoch 5/100
800/800 [==============================] - 1s 932us/step - loss: 0.4135 - accuracy: 0.8329
Epoch 6/100
800/800 [==============================] - 1s 946us/step - loss: 0.4156 - accuracy: 0.8280
Epoch 7/100
800/800 [==============================] - 1s 991us/step - loss: 0.4103 - accuracy: 0.8366
Epoch 8/100
800/800 [==============================] - 1s 988us/step - loss: 0.4099 - accuracy: 0.8296
Epoch 9/100
800/800 [==============================] - 1s 971us/step - loss: 0.3960 - accuracy: 0.8396
Epoch 10/100
800/800 [==============================] - 1s 979us/step - l

In [ ]:
# Predicting the Test set results probability customers might leave the bank
y_pred = classifier.predict(X_test)

#but we need true or flase if customers leave bank or not
#set a threshold here 0.5. if more then true else false
y_pred=(y_pred>0.5)
print(y_pred[0:10])


[[False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]]


In [ ]:
# Making the Confusion Matrix
#(1,1)+(2,2)= 1496+225 correct predictions and
#(1,2)+(2,1)= 180+99 incorrect predictions
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1496   99]
 [ 180  225]]


In [ ]:
#accuraccy 
print((1496+225)/2000)

0.8605
